starter/models/user.py
from starter.extensions import db
from starter.services.github import GitHub

class User(db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    avatar_url = db.Column(db.String(80), nullable=True)
    github_id = db.Column(db.Integer(), nullable=True)

    def __init__(self, username, avatar_url, github_id):
        self.username = username
        self.avatar_url = avatar_url
        self.github_id = github_id
    def find_or_create_from_token(access_token):
        data = GitHub.get_user_from_token(access_token)

        """Find existing user or create new User instance"""
        instance = User.query.filter_by(username=data['login']).first()

        if not instance:
            instance = User(data['login'], data['avatar_url'], data['id'])
            db.session.add(instance)
            db.session.commit()

        return instance

    def find_or_create_from_token(access_token):
        data = GitHub.get_user_from_token(access_token)

        """Find existing user or create new User instance"""
        instance = User.query.filter_by(username=data['login']).first()

        if not instance:
            instance = User(data['login'], data['avatar_url'], data['id'])
            db.session.add(instance)
            db.session.commit()

        return instance

    def __repr__(self):
        return "<User: {}>".format(self.username)

starter/app.py
import os

from flask import Flask, render_template
from starter import settings, controllers, models
from starter.extensions import db, markdown

project_dir = os.path.dirname(os.path.abspath(__file__))

def create_app(config_object=settings):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config_object)

    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app

def register_extensions(app):
    """Register Flask extensions."""
    db.init_app(app)
    markdown.init_app(app)

    with app.app_context():
        db.create_all()
    return None

def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(controllers.public.blueprint)
    app.register_blueprint(controllers.auth.blueprint)
    app.register_blueprint(controllers.github.blueprint)
    return None

def register_errorhandlers(app):
    """Register error handlers."""
    @app.errorhandler(401)
    def internal_error(error):
        return render_template('401.html'), 401

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('404.html'), 404

    @app.errorhandler(500)
    def internal_error(error):
        return render_template('500.html'), 500

    return None

starter/controllers/__init__.py
"""Controllers package"""
from . import auth, github, public

starter/controllers/auth.py
import functools, json, requests

from flask import flash, redirect, render_template, request
from flask import Blueprint, session, url_for, g

from starter.models.user import User
from starter.settings import GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET
from starter.services.github import GitHub

blueprint = Blueprint('auth', __name__, url_prefix='/auth')

github = GitHub(GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET)

@blueprint.route('/github/login')
def githubLogin():
    return redirect(github.authorization_url(scope='public_repo'))

@blueprint.route('/github/callback', methods=('GET', 'POST'))
def githubCallback():
    if 'code' not in request.args:
        return '', 500

    # Fetch user from GitHub OAuth and store in session
    access_token = github.get_token(request.args['code'])

    if access_token is None:
        flash('Could not authorize your request. Please try again.')
        return '', 404

    user = User.find_or_create_from_token(access_token)

    session['access_token'] = access_token
    session['user_id'] = user.id

    return redirect(url_for('public.index'))

@blueprint.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('public.index'))

@blueprint.before_app_request
def get_current_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter_by(id=user_id).first()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

starter/controllers/github.py
from flask import redirect, render_template, request
from flask import Blueprint, flash, url_for, session

from starter.controllers.auth import login_required
from starter.services.github import GitHub

blueprint = Blueprint('github', __name__, url_prefix='/github')

@blueprint.route('/')
def index():
    if not 'access_token' in session:
        flash('Please sign in with your GitHub account.', 'info')
        return render_template('github/index.html')

    github = GitHub(access_token=session['access_token'])

    starred_repos = github.get('/user/starred')
    return render_template('github/index.html', repos=starred_repos)

@blueprint.route('/search')
def search():
    search = request.args.get('query')

    if search is None or search == '':
        flash('Please include a repo name you want to search for.')
        return redirect(url_for('github.index'))
    if not 'access_token' in session:
        flash('Please sign in with your GitHub account.', 'error')
        return redirect(url_for('github.index'))

    github = GitHub(access_token=session['access_token'])

    repos = github.get('/search/repositories', { 'q': search } )
    return render_template('github/index.html', repos=repos['items'])

@blueprint.route('/star', methods=['POST'])
def star():
    repo = request.form['full_name']

    if not 'access_token' in session:
        flash('Please sign in with your GitHub account.', 'error')
        return redirect(url_for('github.index'))

    github = GitHub(access_token=session['access_token'])
    github.delete('/user/starred/' + repo)

    return redirect(url_for('github.index'))

starter/controllers/public.py
from flask import Blueprint, render_template

from starter.extensions import markdown

blueprint = Blueprint('public', __name__)

@blueprint.route('/')
def index():
    with open('README.md', 'r') as input_file:
        text = input_file.read()
        content = markdown.render(text)
        return render_template('home/index.html', body=content)

@blueprint.route('/user-guide')
def user_guide():
    with open('starter/docs/USER_GUIDE.md', 'r') as input_file:
        text = input_file.read()
        content = markdown.render(text)
        return render_template('home/index.html', body=content)

@blueprint.route('/getting-started')
def getting_started():
    with open('starter/docs/GETTING_STARTED.md', 'r') as input_file:
        text = input_file.read()
        content = markdown.render(text)
        return render_template('home/index.html', body=content)

starter/views/public.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for, session
)

from starter.views.auth import login_required

blueprint = Blueprint('public', __name__)

@blueprint.route('/')
def index():
    return render_template('home/index.html')

@blueprint.route('/about')
def about():
    # TODO: Create this template
    return render_template('home/index.html')

@blueprint.route('/getting-started')
def getting_started():
    # TODO: Create this template
    return render_template('home/index.html')

starter/templates/home/index.html
{% extends 'layout.html' %}

{% block header %}
  <div class='bg-dark text-light'>
    <div class='container py-5 my-4'>
      <h1 class='h3 mb-1'>Hackathon Starter Kit</h1>
      <h2 class='h6 text-secondary'>Presented by GitHub & MLH</h2>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class='container my-5'>
    {% if body %}
      <div class='content markdown'>{{ body|safe }}</div>
    {% endif %}
  </div>
{% endblock %}

starter/templates/layout.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    {% block head %}
    <meta charset='utf-8'>
    <title>{Project Name}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" >
    <link rel="stylesheet" href="{{ url_for('static', filename='markdown.min.css') }}" >
    {% endblock %}
  </head>
  <body class='d-flex flex-column' style='min-height: 100vh;'>
    {% include 'nav.html' %}

    {% include 'flash.html' %}

    {% block header %}{% endblock %}

    <div class='content' style='flex-grow: 1;'>
      {% block content %}{% endblock %}
    </div>

    {% include 'footer.html' %}
  </body>
</html>

starter/templates/nav.html
<nav class="navigation container">
  <div class="d-flex flex-column flex-sm-row justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <a href="/" class="text-decoration-none text-dark">
        <h1 class="h5 m-0">{Project Name}</h1>
      </a>
      <a class="nav-item p-2 m-1" href="{{ url_for('github.index') }}">
        GitHub API
      </a>
    </div>
    <div class="d-flex align-items-center">
      {% if g.user %}
        <span class="nav-item p-2 text-secondary d-flex align-items-center">
          <img src="{{ g.user['avatar_url'] }}" class='rounded mr-2' style='width:24px; height:24px;'/>
          {{ g.user['username'] }}
        </span>
      {% endif %}
      <span class="nav-item p-2 m-1">
        <a href="{{ url_for('public.user_guide') }}">Docs</a>
      </span>
      <span class="nav-item p-2 m-1">
        <a href="{{ url_for('public.getting_started') }}">Getting Started</a>
      </span>
      {% if g.user %}
        <span class="nav-item p-2 m-1">
          <a href="{{ url_for('auth.logout') }}">Log out</a>
        </span>
      {% else %}
        <span class="nav-item p-2 m-1">
          <a href="{{ url_for('auth.githubLogin') }}">Login with GitHub</a>
        </span>
      {% endif %}
    </div>
  </div>
</nav>