app/controllers/tutorial.py
# -*- coding: utf-8 -*-
from flask import redirect, render_template, request
from flask import g, Blueprint, flash, url_for, session

from app.services.github import GitHub

blueprint = Blueprint('tutorial', __name__, url_prefix='/bites')


@blueprint.route('/contribute')
def contribute():
    search = request.args.get('query', '')
    if not 'access_token' in session:
        flash('This tutorial needs an authenticated user to make the request. Please sign in with your GitHub account.',
              'danger')
        return render_template('tutorial/requesting.html')

    github = GitHub(access_token=session['access_token'])
    results1 = github.get('/user/starred')
    results2 = github.get('/search/repositories', {'q': search})
    results2 = results2.get('items', [])

    return render_template('tutorial/requesting.html',
                           tutorial1=results1[:5],
                           tutorial2=results2[:5],
                           query=search
                           )


@blueprint.route('/history')
def history():
    search = request.args.get('query', '')
    if not 'access_token' in session:
        flash('This tutorial needs an authenticated user to make the request. Please sign in with your GitHub account.',
              'danger')
        return render_template('tutorial/history.html')

    github = GitHub(access_token=session['access_token'])
    results1 = github.get('/user/starred')
    results2 = github.get('/search/repositories', {'q': search})
    results2 = results2.get('items', [])

    return render_template('tutorial/history.html',
                           tutorial1=results1[:5],
                           tutorial2=results2[:5],
                           query=search
                           )


@blueprint.route('/star', methods=['POST'])
def star():
    repo = request.form['full_name']

    if not 'access_token' in session:
        flash('Please sign in with your GitHub account.', 'danger')
        return redirect(url_for('github.fetching'))

    github = GitHub(access_token=session['access_token'])
    github.delete('/user/starred/' + repo)

    return redirect(url_for('tutorial.fetching'))

app/views/auth.py
# -*- coding: utf-8 -*-
import functools, json, requests

from flask import flash, redirect, render_template, request
from flask import Blueprint, session, url_for, g

from app.models.user import User
from app.settings import GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET
from app.services.github import GitHub

blueprint = Blueprint('auth', __name__, url_prefix='/auth')

@blueprint.route('/login/github')
def githubLogin():
    github = GitHub(GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET)
    return redirect(github.authorization_url(scope='public_repo'))

@blueprint.route('/callback/github', methods=('GET', 'POST'))
def githubCallback():
    if 'code' not in request.args:
        return '', 500

    # Fetch user from GitHub OAuth and store in session
    github = GitHub(GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET)
    access_token = github.get_token(request.args['code'])

    if access_token is None:
        flash('Could not authorize your request. Please try again.', 'danger')
        return '', 404

    user = User.find_or_create_from_token(access_token)

    session['access_token'] = access_token
    session['user_id'] = user.id

    return redirect(url_for('home.index'))

@blueprint.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('home.index'))

@blueprint.before_app_request
def get_current_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter_by(id=user_id).first()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

app/templates/partials/flash.html
{% for category, message in get_flashed_messages(with_categories=true) %}
  <div class="alert alert-{{ category if category != None else 'danger' }} mb-0 rounded-0">
    <div class="container">
      {{ message }}
    </div>
  </div>
{% endfor %}

app/templates/partials/footer.html
{% block footer %}
  {# Add a global footer here if you like #}
{% endblock %}

app/templates/partials/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-gray-dark text-white">
  <div class="container">
    <a class="text-white link-reset text-inherit pr-3" href="/">
      <img src="{{ url_for('static', filename='img/logo.png') }}" style="width:42px" alt="Imfull">
      Im<strong>full</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Bites
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('tutorial.history' )}}">Ort Report</a>
            <a class="dropdown-item" href="{{ url_for('tutorial.contribute' )}}"><code>Contribute</code></a>
          </div>
        </li>
        {% if g.user %}
          <li class="nav-item p-2 pr-3">
            <img src="{{ g.user['avatar_url'] }}" class='rounded mr-2' style='width:24px;height:24px;'/>
            {{ g.user['username'] }}
          </li>
          <li class="nav-item">
            <a class="nav-link text-inherit" href="{{ url_for('auth.logout') }}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link text-inherit" href="{{ url_for('auth.githubLogin') }}">
              Login with GitHub
            </a>
          </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>